name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"
          enable-cache: true

      - name: Setup
        run: make setup

      - name: Lint
        run: make lint

      - name: Tests
        run: make test
